title: Grammar.Guru
description: CSET Linguistics and more
author: Grammar.Guru
github: https://github.com/CMarcille
about: Passing the CSET Language, Linguistics, and Literacy test is hard! I'm here to help.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/logo.png

enableTags: true
tagarray: []

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/CMarcille"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

url: "https://vijay07roy.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
